cc=gcc

libsyscalldemo: libsyscalldemo.o
	$(cc) libsyscalldemo.o -o libsyscalldemo
libsyscalldemo.o:libsyscalldemo.c
	$(cc) -c libsyscalldemo.c -o libsyscalldemo.o
clean:
	rm -f libsyscalldemo.o libsyscalldemo
